"""define blacklist token model

Revision ID: 05398966fbf0
Revises: d470411f8891
Create Date: 2019-12-10 17:11:05.993940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05398966fbf0'
down_revision = 'd470411f8891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
