"""change some activity column names

Revision ID: 81325a3b1f04
Revises: da6111ec00af
Create Date: 2019-12-19 17:59:34.119976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81325a3b1f04'
down_revision = 'da6111ec00af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('activity_type', sa.String(length=50), nullable=False))
    op.add_column('activities', sa.Column('occured_at', sa.DateTime(), nullable=False))
    op.drop_column('activities', 'occuredAt')
    op.drop_column('activities', 'activityType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('activityType', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('occuredAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('activities', 'occured_at')
    op.drop_column('activities', 'activity_type')
    # ### end Alembic commands ###
