"""Include more details on user model

Revision ID: d470411f8891
Revises: 07d392ebf9e1
Create Date: 2019-12-10 14:22:52.807884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'd470411f8891'
down_revision = '07d392ebf9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=20), nullable=True))

    users_first_name = table('users', column('first_name'))
    users_is_active = table('users', column('is_active'))
    users_last_name = table('users', column('last_name'))
    users_is_email_verified = table('users', column('is_email_verified'))

    op.execute(users_first_name.update().values(first_name=''))
    op.execute(users_is_active.update().values(is_active=True))
    op.execute(users_last_name.update().values(last_name=''))
    op.execute(users_is_email_verified.update().values(is_email_verified=False))

    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'last_name', nullable=False)
    op.alter_column('users', 'is_active', nullable=False)
    op.alter_column('users', 'is_email_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_email_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
