"""define activity model to store user activities

Revision ID: da6111ec00af
Revises: 81261b2b3706
Create Date: 2019-12-19 17:21:33.705043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6111ec00af'
down_revision = '81261b2b3706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('occuredAt', sa.DateTime(), nullable=False),
    sa.Column('activityType', sa.String(length=50), nullable=False),
    sa.Column('sign_up_token', sa.String(length=300), nullable=True),
    sa.Column('sign_in_token', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('old_email', sa.String(length=100), nullable=True),
    sa.Column('new_email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    # ### end Alembic commands ###
